services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent data storage

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp"  # Traces UDP
      - "14268:14268"  # Traces HTTP 
      - "4317:4317"  # Jaeger gRPC endpoint
      - "4318:4318"  # OpenTelemetry HTTP
  
  api-gateway:
    image: kong:3.9
    environment:
      KONG_DATABASE: "off"
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'  # Disable database mode
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_DECLARATIVE_CONFIG: '/kong/config.yaml'
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For local development
    volumes:
      - './docker/kong/config.yaml:/kong/config.yaml'
    ports:
      - "8000:8000"  # Proxy (API)
      - "8001:8001"  # Admin API
      - "8002:8002"  # Admin UI
      - "8443:8443"  # Proxy (HTTPS)
      - "8444:8444"  # Admin API (HTTPS)

volumes:
  rabbitmq_data: