name: Deploy Monorepo

on:
  push:
    branches:
      - main

jobs:

  # 🔧 Deploy da Infraestrutura com Pulumi
  deploy-infra:
    name: Deploy Infraestrutura
    runs-on: ubuntu-latest
    if: github.event.head_commit.modified && (
        contains(join(github.event.head_commit.modified, ' '), 'infra/') ||
        contains(join(github.event.head_commit.added, ' '), 'infra/')
      )

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'infra/package-lock.json'

      - name: Install dependencies
        working-directory: ./infra
        run: npm install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Infra with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          work-dir: ./infra
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ""

  # 🚀 Deploy App Orders
  deploy-app-orders:
    name: Deploy App Orders
    runs-on: ubuntu-latest
    needs: deploy-infra
    if: github.event.head_commit.modified && (
        contains(join(github.event.head_commit.modified, ' '), 'app-orders/') ||
        contains(join(github.event.head_commit.added, ' '), 'app-orders/')
      )

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'app-orders/package-lock.json'

      - name: Install dependencies
        working-directory: ./app-orders
        run: npm install --frozen-lockfile

      - name: Build Docker Image
        working-directory: ./app-orders
        run: docker build -t app-orders .

  # 🚀 Deploy App Invoices
  deploy-app-invoices:
    name: Deploy App Invoices
    runs-on: ubuntu-latest
    needs: deploy-infra
    if: github.event.head_commit.modified && (
        contains(join(github.event.head_commit.modified, ' '), 'app-invoices/') ||
        contains(join(github.event.head_commit.added, ' '), 'app-invoices/')
      )

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'app-invoices/package-lock.json'

      - name: Install dependencies
        working-directory: ./app-invoices
        run: npm install --frozen-lockfile

      - name: Build Docker Image
        working-directory: ./app-invoices
        run: docker build -t app-invoices .
